include:
  - board: seeeduino_xiao_ble
    shield: chippy_left
    cmake-args: -DCONFIG_ZMK_POINTING=y
  - board: seeeduino_xiao_ble
    shield: chippy_right
    cmake-args: -DCONFIG_ZMK_POINTING=y
# there is no settingsreset (needed) for the XIAO
